# Generated by Django 5.0 on 2024-01-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_book_is_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_favourite",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
