# Generated by Django 5.0 on 2024-01-02 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Cart"},
        ),
    ]
