# Generated by Django 5.0 on 2024-01-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_cart_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blocked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
