# Generated by Django 5.0 on 2024-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_customuser_blocked_customuser_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=5),
        ),
    ]
